---

- name: "copy backend artifacts"
  copy:
    src: artifact.tar.gz
    dest: artifact.tar.gz
    owner: ubuntu

- name: "extract backend artifacts"
  shell: >
    mkdir ~/backend && tar -zxvf artifact.tar.gz -C ~/backend

- name: "install nvm."
  # Your code here
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: Setup .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
    create: yes

- name: "Install nodeJS, pm2 and start backend service"
  shell: |
    source ~/.nvm/nvm.sh && nvm install 13.8
    npm install -g pm2
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/node/v13.8.0"

    